export const products = [
  {
    id: 1,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 1300,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#66504f'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 2,
    name: 'GAP Stylish long sleeve shirt',
    price: 1700,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#66504f', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'm'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 3,
    name: 'Firstly Comfortable Shoes for Men',
    price: 1900,
    image: '.././images/asset-2.png',
    colors: ['#66504f', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'm'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 4,
    name: 'Apron Game controller for Xbox',
    price: 1500,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#66504f'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['xs', 's', 'm'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 5,
    name: 'Belt Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 6,
    name: 'Cap Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#f00a00'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'm'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 7,
    name: 'Dress Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#f00a00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: [],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 8,
    name: 'Earrings Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#f00a00', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: [],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 9,
    name: 'Headphones Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#f00a00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 10,
    name: 'Jacket Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#f00a00'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: [],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 11,
    name: 'Kilt Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#f00a00', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: [],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 12,
    name: 'Life-jacket Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#f00a00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: [],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 13,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#f00a00', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 14,
    name: 'Necklace Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#00ff00', '#f00a00'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: [],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 15,
    name: 'Overalls Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#f00a00'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: [],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 16,
    name: 'Pyjamas Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: [],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 17,
    name: 'Quilted jacket Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: [, '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 18,
    name: 'Raincoat Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: [],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 19,
    name: 'Sandals Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: [],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 20,
    name: 'T-Shirt Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#00ff00'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: [],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 21,
    name: 'Underpants Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 22,
    name: 'Veil Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: [],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 23,
    name: 'Watch Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: [],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 24,
    name: 'Waistcoat Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: [],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 25,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 26,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['l', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 27,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['xl', 'xxl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 28,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['l', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 29,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['m', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 30,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 31,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['l', 'xl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 32,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 33,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 34,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['l', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 35,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['l', 'xl', 'xxl', 'm'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 36,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['l', 'xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 37,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 38,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['l', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 39,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['l', 'xl', 'xxl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 40,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['l', 'xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 41,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 42,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 43,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'xl', 'xxl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 44,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['xs', 's', 'xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 45,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 46,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 47,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'xl', 'xxl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 48,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['xs', 's', 'xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 49,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 50,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['xs', 's', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 51,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['s', 'xl', 'xxl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 52,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['s', 'xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 53,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 54,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['s', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 55,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['s', 'xl', 'xxl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 56,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['s', 'xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 57,
    name: 'Multicolor Cotton long sleeve shirt for men',
    price: 7850,
    image: '.././images/asset-4.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Aeropostale ',
    category: "Men's Clothing",
    shipping: true,
    cashOnDelivery: true,
    pattern: 'chackered',
    febric: 'Cotton Blend',
    size: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
    country: 'Bangladesh',
    stars: 4.9,
    discount: 10,
  },
  {
    id: 58,
    name: 'GAP Stylish long sleeve shirt',
    price: 5555,
    image: '.././images/asset-1.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Antony Morato',
    category: 'Headhpone',
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: '',
    size: ['s', 'xl', 'xxl'],
    country: 'USA',
    stars: 4,
    discount: 10,
  },
  {
    id: 59,
    name: 'Firstly Comfortable Shoes for Men',
    price: 2850,
    image: '.././images/asset-2.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Arrow ',
    category: "Men's Bag",
    shipping: true,
    cashOnDelivery: false,
    pattern: '',
    febric: '',
    size: ['s', 'xl', 'xxl'],
    country: 'Germany',
    stars: 3,
    discount: 10,
  },
  {
    id: 60,
    name: 'Microsoft Game controller for Xbox',
    price: 22850,
    image: '.././images/asset-3.png',
    colors: ['#ff0000', '#00ff00', '#0000ff'],
    brand: 'Raymond ',
    category: "Men's Watch",
    shipping: true,
    cashOnDelivery: true,
    pattern: '',
    febric: ' ',
    size: ['s', 'xl', 'xxl'],
    country: 'Italy',
    stars: 4.9,
    discount: 10,
  },
]
